### ISSUE TITLE
RETRIEVE 50.007801 UL_WLD_USDC  ON WLD NETWORK

### ISSUE THREAD

**Issue by Phixperiam** [blockscout/.github#14]
[
![Screenshot_20241124-110233_Binance](https://github.com/user-attachments/assets/5b952c9f-7d77-4d99-9dc4-897c6d232420)
](url)

Would like to retrieve 50.007801 UL_WLD_USDC
Deposit Address
0x17861f26912374c4c4cb0abf804e809b87409e1c

Sent to
0xb97f9D7efFE8126F3C8C6EE1e66f63c549791145

Transaction hash

0x37663057012f1d445bbb001fbab02557ad78624c848f17ecc3d0723471b132cd

**Comment by Phixperiam** [comment]
You can reach me on Email : philiam.ap@gmail.com

**Comment by alialobidm** [comment]
[](url)
